name: foam
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - scikit-image=0.22
  - porespy
  - pypardiso
  - dask-image
  - dask-labextension
  - zarr
  - seaborn
  - matplotlib-scalebar
  - openpyxl
  - pyqt
  - napari
